###
get http://localhost:8080/

###
get http://localhost:8080/api/words/

###
get http://localhost:8080/api/words?sortable=eng&sortOrder=asc

###
get http://localhost:8080/api/words/1

###
delete http://localhost:8080/api/words/1

###
post http://localhost:8080/api/words/
content-type: application/json

{ "english_word": "France", "finnish_word": "Ranska", "category_tags": "country"}

###
put http://localhost:8080/api/words/0
content-type: application/json

{ "english_word": "Sweden", "finnish_word": "Ruotsi", "category_tags": "countries" }

###
patch http://localhost:8080/api/words/3
content-type: application/json

{ "category_tags": "countries"}

###
get http://localhost:8080/api/scores/

###
get http://localhost:8080/api/scores/1

######
delete http://localhost:8080/api/scores/1

###
post http://localhost:8080/api/scores/
content-type: application/json

{ "score": "2/4", "correct_words": "coffee, France", "incorrect_words": "tea, Spain"}